export class AssociatesService {
   associates: object[] | any = [
      {city: 'Aleksinac ', person: 'Dejan' },
      {city: 'Alibunar ', person: 'Željko' },
      {city: 'Apatin ', person: 'Velja' },
      {city: 'Aranđelovac ', person: 'Dejan, Marko' },
      {city: 'Bačka Palanka ', person: 'Vladimir' },
      {city: 'Bačka Topola ', person: 'Marčeta, Fofo Šlep' },
      {city: 'Bajina Bašta ', person: 'Mirko' },
      {city: 'Batočina ', person: 'Ivan' },
      {city: 'Batrovan ', person: 'Živan' },
      {city: 'Bečej ', person: 'Žika šlep' },
      {city: 'Bela Crkva ', person: 'Srđan M' },
      {city: 'Beograd', person: 'Aleksandar, Branislav, Duško, Zoran ' },
      {city: 'Bor ', person: 'Aca' },
      {city: 'Brus ', person: 'Pavlović' },
      {city: 'Bujanovac ', person: 'Leon' },
      {city: 'Čačak ', person: 'Ivan' },
      {city: 'Čajetina ', person: 'Dragan' },
      {city: 'Donji Milanovac ', person: 'Igor' },
      {city: 'Gornji Milanovac ', person: 'Zoran' },
      {city: 'Ivanjica ', person: 'Saša Popović' },
      {city: 'Jagodina ', person: 'Enis' },
      {city: 'Kikinda ', person: 'Rade, Petar' },
      {city: 'Kladovo ', person: 'Zlatko' },
      {city: 'Knjaževac ', person: 'Darko, Dragan, Joca' },
      {city: 'Kovačica ', person: 'Adam' },
      {city: 'Kragujevac ', person: 'Jole' },
      {city: 'Kraljevo ', person: 'Mujo' },
      {city: 'Kruševac ', person: 'Mile, Nemanja' },
      {city: 'Kučevo ', person: 'Vlada, Goran' },
      {city: 'Kuršumlija ', person: 'Ljubodrag' },
      {city: 'Lazarevac ', person: 'Mišković' },
      {city: 'Leskovac ', person: 'Goran' },
      {city: 'Ljig ', person: 'Milovan' },
      {city: 'Ljubovija ', person: 'Dragan Jovanović' },
      {city: 'Loznica ', person: 'Milorad' },
      {city: 'Majdanpek ', person: 'Goran' },
      {city: 'Mladenovac ', person: 'Ivan' },
      {city: 'Mol (Ada) ', person: 'Danijel' },
      {city: 'Negotin ', person: 'Dragan Džanko' },
      {city: 'Niš ', person: 'Slaviša, Raka' },
      {city: 'Nova Varoš  ', person: 'Martinović' },
      {city: 'Novi Pazar ', person: 'Rašid' },
      {city: 'Novi Sad ', person: 'Jašo, Vlada, Jovan, Vladan Mitrić, Srđan, Toma, Peđa' },
      {city: 'Obrenovac ', person: 'Zoran' },
      {city: 'Odžaci ', person: 'Saša' },
      {city: 'Pančevo ', person: 'Jovan' },
      {city: 'Pirot ', person: 'Radiša' },
      {city: 'Plandište  ', person: 'Ćuk' },
      {city: 'Požarevac ', person: 'Nikola' },
      {city: 'Požega ', person: 'Mihajlo' },
      {city: 'Prijepolje ', person: 'Gazo' },
      {city: 'Raška ', person: 'Aco Mutavdžič' },
      {city: 'Ražanj ', person: 'Lilko' },
      {city: 'Ruma ', person: 'Goran' },
      {city: 'Šabac ', person: 'Aleksandar, Meda, Boban' },
      {city: 'Sjenica ', person: 'Eme' },
      {city: 'Smederevo ', person: 'Borivoje' },
      {city: 'Soko Banja ', person: 'Milan' },
      {city: 'Sombor ', person: 'Džafa' },
      {city: 'Sopot ', person: 'Darko' },
      {city: 'Sremska Mitrovica ', person: 'Slobodan' },
      {city: 'Subotica ', person: 'Đorđe, Mario, Srđan' },
      {city: 'Surčin', person: 'Darko, Boža, Duško Basarak, AC Krainić ' },
      {city: 'Svilajnac ', person: 'Zoran' },
      {city: 'Titel ', person: 'Peca' },
      {city: 'Trstenik ', person: 'Đurić' },
      {city: 'Užice ', person: 'Gardašević, Jevtović' },
      {city: 'Valjevo ', person: 'Miloš Savić' },
      {city: 'Velika Plana  ', person: 'Bojan' },
      {city: 'Vladičin Han ', person: 'Vladica' },
      {city: 'Vranje ', person: 'Bojan' },
      {city: 'Vrbas ', person: 'Bata' },
      {city: 'Vrdnik ', person: 'Igor' },
      {city: 'Vršac ', person: 'Vedran' },
      {city: 'Žabalj ', person: 'Zoran' },
      {city: 'Zaječar Auto ', person: 'Bane' },
      {city: 'Zmajevo ', person: 'Goran' },
      {city: 'Zrenjanin ', person: 'Srđan' },     
   ]
}